from __future__ import annotations

from enum import StrEnum


class TaskState(StrEnum):
    DRAFT = "DRAFT"
    INVESTIGATING = "INVESTIGATING"
    AWAITING_CLARIFICATION = "AWAITING_CLARIFICATION"
    AWAITING_PLAN_APPROVAL = "AWAITING_PLAN_APPROVAL"
    READY_TO_EXECUTE = "READY_TO_EXECUTE"
    EXECUTING = "EXECUTING"
    AWAITING_ACTION_APPROVAL = "AWAITING_ACTION_APPROVAL"
    AWAITING_BUDGET_APPROVAL = "AWAITING_BUDGET_APPROVAL"
    VERIFYING = "VERIFYING"
    AWAITING_USER_CONFIRMATION = "AWAITING_USER_CONFIRMATION"
    READY_TO_APPLY = "READY_TO_APPLY"
    APPLYING = "APPLYING"
    ROLLING_BACK = "ROLLING_BACK"
    RECOVERY_REQUIRED = "RECOVERY_REQUIRED"
    AWAITING_PROVIDER_UNLOCK = "AWAITING_PROVIDER_UNLOCK"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    NOT_APPLIED = "NOT_APPLIED"
    COMPLETED = "COMPLETED"


TERMINAL_STATES = frozenset(
    {
        TaskState.COMPLETED,
        TaskState.NOT_APPLIED,
        TaskState.FAILED,
        TaskState.CANCELLED,
    }
)


class TransitionTrigger(StrEnum):
    SUBMIT_TASK = "SUBMIT_TASK"
    REQUEST_CLARIFICATION = "REQUEST_CLARIFICATION"
    PERSIST_PLAN = "PERSIST_PLAN"
    SUBMIT_CLARIFICATION = "SUBMIT_CLARIFICATION"
    CONTINUE_INVESTIGATION = "CONTINUE_INVESTIGATION"
    APPROVE_PLAN = "APPROVE_PLAN"
    REJECT_PLAN = "REJECT_PLAN"
    CONTINUE_EXECUTION = "CONTINUE_EXECUTION"
    PROVIDER_LOCKED = "PROVIDER_LOCKED"
    REQUEST_ACTION_APPROVAL = "REQUEST_ACTION_APPROVAL"
    APPROVE_ACTION = "APPROVE_ACTION"
    REJECT_ACTION = "REJECT_ACTION"
    REQUEST_BUDGET_REAPPROVAL = "REQUEST_BUDGET_REAPPROVAL"
    APPROVE_BUDGET = "APPROVE_BUDGET"
    REJECT_BUDGET = "REJECT_BUDGET"
    REVISE_PLAN = "REVISE_PLAN"
    START_VERIFICATION = "START_VERIFICATION"
    REQUEST_USER_CONFIRMATION = "REQUEST_USER_CONFIRMATION"
    VERIFICATION_PASSED = "VERIFICATION_PASSED"
    VERIFICATION_FEEDBACK = "VERIFICATION_FEEDBACK"
    CONFIRM_USER_ACCEPTANCE = "CONFIRM_USER_ACCEPTANCE"
    REJECT_USER_ACCEPTANCE = "REJECT_USER_ACCEPTANCE"
    CONFIRM_APPLY = "CONFIRM_APPLY"
    REJECT_APPLY = "REJECT_APPLY"
    APPLY_SUCCEEDED = "APPLY_SUCCEEDED"
    APPLY_FAILED = "APPLY_FAILED"
    ROLLBACK_SUCCEEDED = "ROLLBACK_SUCCEEDED"
    ROLLBACK_RECOVERY_REQUIRED = "ROLLBACK_RECOVERY_REQUIRED"
    REQUEST_RECOVERY = "REQUEST_RECOVERY"
    CONTINUE_PROVIDER_UNLOCK = "CONTINUE_PROVIDER_UNLOCK"
    CONTINUE_BLOCKED_EXECUTION = "CONTINUE_BLOCKED_EXECUTION"
    SUBMIT_BLOCKED_CLARIFICATION = "SUBMIT_BLOCKED_CLARIFICATION"
    CONTINUE_APPLY_CONFLICT = "CONTINUE_APPLY_CONFLICT"
    CANCEL_TASK = "CANCEL_TASK"
    ENTER_BLOCKED = "ENTER_BLOCKED"
    FAIL_UNRECOVERABLY = "FAIL_UNRECOVERABLY"


class TransitionReason(StrEnum):
    PERMITTED = "PERMITTED"
    ILLEGAL_TRANSITION = "ILLEGAL_TRANSITION"
    TERMINAL_STATE = "TERMINAL_STATE"
    EXPECTED_STATE_CONFLICT = "EXPECTED_STATE_CONFLICT"
    EXPECTED_VERSION_CONFLICT = "EXPECTED_VERSION_CONFLICT"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    PRECONDITION_FAILED = "PRECONDITION_FAILED"
    INVALID_REASON = "INVALID_REASON"
    UNCERTAIN_EFFECT_RECOVERY = "UNCERTAIN_EFFECT_RECOVERY"
    RECOVERY_ALREADY_REQUIRED = "RECOVERY_ALREADY_REQUIRED"


class BlockedReason(StrEnum):
    BLOCKED_MISSING_DEPENDENCY = "BLOCKED_MISSING_DEPENDENCY"
    BLOCKED_UNSUPPORTED_CAPABILITY = "BLOCKED_UNSUPPORTED_CAPABILITY"
    DOCKER_UNAVAILABLE = "DOCKER_UNAVAILABLE"
    PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"
    CONTEXT_EXPORT_DENIED = "CONTEXT_EXPORT_DENIED"
    APPLY_CONFLICT = "APPLY_CONFLICT"
    BLOCKED_POLICY_ERROR = "BLOCKED_POLICY_ERROR"
    PROVIDER_CONFIGURATION_ERROR = "PROVIDER_CONFIGURATION_ERROR"
    PERSISTENCE_FAILED = "PERSISTENCE_FAILED"
    BUDGET_EXTENSION_REJECTED = "BUDGET_EXTENSION_REJECTED"
    USER_ACCEPTANCE_REJECTED = "USER_ACCEPTANCE_REJECTED"


class UnrecoverableFailureReason(StrEnum):
    INVALID_ACTION = "INVALID_ACTION"
    HARD_LIMIT_REACHED = "HARD_LIMIT_REACHED"
    PROVIDER_RESPONSE_INVALID = "PROVIDER_RESPONSE_INVALID"
    OUTPUT_LIMIT = "OUTPUT_LIMIT"
    CREATE_FAILED = "CREATE_FAILED"
    START_FAILED = "START_FAILED"
    RESOURCE_LIMIT = "RESOURCE_LIMIT"


class IdempotencyStatus(StrEnum):
    NEW = "NEW"
    REPLAYED = "REPLAYED"
    CONFLICT = "CONFLICT"
