from __future__ import annotations

from enum import StrEnum


class PolicyReason(StrEnum):
    ALLOWED = "ALLOWED"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    DENIED_CAPABILITY = "DENIED_CAPABILITY"
    BLOCKED_POLICY_ERROR = "BLOCKED_POLICY_ERROR"
    BLOCKED_UNSUPPORTED_CAPABILITY = "BLOCKED_UNSUPPORTED_CAPABILITY"


class PolicyErrorCode(StrEnum):
    INVALID_POLICY_CONTEXT = "INVALID_POLICY_CONTEXT"
    UNKNOWN_ACTION = "UNKNOWN_ACTION"
    POLICY_EVALUATION_FAILURE = "POLICY_EVALUATION_FAILURE"
    INVALID_DECISION_CONSTRUCTION = "INVALID_DECISION_CONSTRUCTION"
